FROM library/node:10-alpine
RUN apk update && apk upgrade && apk add --no-cache git
ENV NODE_ENV production
RUN mkdir -p /usr/src
WORKDIR /usr/src
ADD https://www.worldtimeserver.com/ /usr/src
RUN git clone https://github.com/Minhaj-ul-abidin/three_js_solarsystem.git
RUN mv three_js_solarsystem app
WORKDIR /usr/src/app
RUN npm install && npm cache clean --force
ENV PORT 80
EXPOSE 80
CMD [ "npm", "start" ]
